var fs=require("fs")
fs.mkdirSync("node")
fs.writeFileSync("node/write.txt","Be kind")
fs.appendFileSync("node/write.txt"," to one another")
data=fs.readFileSync("node/write.txt","UTF-8")
console.log(data)
data=fs.readFileSync("node/write.txt")
console.log(data)
console.log(data.toString())
fs.renameSync("node/write.txt","node/newwrite.txt")
fs.unlinkSync("node/newwrite.txt")
fs.rmdirSync("node")