var pm=require("path")
path=pm.basename("E:/FSD-2/fs_copy.js")
console.log(path)
console.log("...........")
path1=pm.dirname("E:/FSD-2/fs_copy.js")
console.log(path1)
console.log("...........")
ext=pm.extname("E:/FSD-2/fs_copy.js")
console.log(ext)
console.log("...........")
path2=pm.parse("E:/FSD-2/fs_copy.js")
console.log(path2)
console.log("...........")